from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class NBAStats(db.Model):
    PLAYER_ID = db.Column(db.String(255), primary_key=True)
    RANK = db.Column(db.Integer)
    PLAYER = db.Column(db.String(255))  
    TEAM_ID = db.Column(db.String(255))
    TEAM = db.Column(db.String(255))
    GP = db.Column(db.Integer)
    MIN = db.Column(db.Integer)
    FGM = db.Column(db.Integer)
    FGA = db.Column(db.Integer)
    FG_PCT = db.Column(db.Float)
    FG3M = db.Column(db.Integer)
    FG3A = db.Column(db.Integer)
    FG3_PCT = db.Column(db.Float)
    FTM = db.Column(db.Integer)
    FTA = db.Column(db.Integer)
    FT_PCT = db.Column(db.Float)
    OREB = db.Column(db.Integer)
    DREB = db.Column(db.Integer)
    REB = db.Column(db.Integer)
    AST = db.Column(db.Integer)
    STL = db.Column(db.Integer)
    BLK = db.Column(db.Integer)
    TOV = db.Column(db.Integer)
    PTS = db.Column(db.Integer)
    EFF = db.Column(db.Integer)

class TeamsRegularSeason(db.Model):
    __tablename__ = 'teams_regular_season'

    rank = db.Column(db.Integer)
    team_name = db.Column(db.String(255))
    games_played = db.Column(db.Integer)
    wins = db.Column(db.Integer)
    losses = db.Column(db.Integer)
    win_percentage = db.Column(db.Float)
    minutes = db.Column(db.Integer)
    points = db.Column(db.Integer)
    field_goals_made = db.Column(db.Integer)
    field_goals_attempted = db.Column(db.Integer)
    field_goals_percentage = db.Column(db.Float)
    three_pointers_made = db.Column(db.Integer)
    three_pointers_attempted = db.Column(db.Integer)
    three_point_percentage = db.Column(db.Float)
    free_throws_made = db.Column(db.Integer)
    free_throws_attempted = db.Column(db.Integer)
    free_throws_percentage = db.Column(db.Float)
    offensive_rebounds = db.Column(db.Integer)
    defensive_rebounds = db.Column(db.Integer)
    total_rebounds = db.Column(db.Integer,primary_key=True)
    assists = db.Column(db.Integer)
    turnovers = db.Column(db.Integer)
    steals = db.Column(db.Integer)
    blocks = db.Column(db.Integer)
    opponent_blocks = db.Column(db.Integer)
    personal_fouls = db.Column(db.Integer)
    personal_fouls_drawn = db.Column(db.Integer)
    plus_minus = db.Column(db.Float)
